### ISSUE TITLE
Correction Bug mineur

### ISSUE THREAD

**Issue by Panzershrekk** [recipyhq/recipy-mobile#50]
J'écris ici la liste des bug à corriger(à compléter au fur et à mesure des découvertes d'autres bug)

- [x] Message d'erreur quand on à pas de carnet de recette sur les screen Description de recette et Mes carnets de recettes. (Pb identifié mais pas corrigé)
- [x] Problème de refresh sur la page Description d'une recette des listes de courses/carnet de recettes (dans le modal) quand on créer liste de course/carnet de recette sans reload la description
- [ ] Les checkbox de la liste de courses à la consultation se coche mais ne se décoche pas
- [x] Hitbox des boutons pour consulter la liste de course trop petite
- [x] L'ajout à une liste existant fail quand la liste contient des espaces

**Comment by guillobits** [comment]
A faire au plus vite pour un lancement de BETA. ;)
Au besoin on lancera en BETA sans ces modifications puis on les passera en prod comme correctif retour de BETA.

**Comment by guillobits** [comment]
- [ ] En plus : Ajouter un test d'être connecté avant de get les recipe book sur une fiche recette
