### ISSUE TITLE
Mobile | Création compte

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy-mobile#57]
Impossible de créer un compte sur Mobile, avec les adresses Gmail et Wanadoo, les emails de confirmations n'arrivent jamais ni mêem dans les pourriels.

**Comment by guillobits** [comment]
Il semble que l'appel n'est pas fait ou ne fonctionne pas malgrès le message de succès sur le mobile.
J'ai créé un compte il n'est pas ajouté dans l'admin...
A corriger rapidement.

**Comment by guillobits** [comment]
Semble lié au dernier changement sur la route d'inscription. Il faut à présent appeler user.json

**Comment by Thornolf** [comment]
C'est bon du coup c'est fix ?
